
package org.azuremd.backend.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Azure", targetNamespace = "http://webservice.backend.azuremd.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Azure {


    /**
     * 
     * @param authToken
     * @param vmId
     * @param sourceUrl
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "RegisterVm")
    @WebResult(partName = "return")
    public SystemStatus registerVm(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId,
        @WebParam(name = "sourceUrl", partName = "sourceUrl")
        String sourceUrl);

    /**
     * 
     * @param authToken
     * @param vmId
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "StartVm")
    @WebResult(partName = "return")
    public SystemStatus startVm(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId);

    /**
     * 
     * @param authToken
     * @param vmId
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "RestartVm")
    @WebResult(partName = "return")
    public SystemStatus restartVm(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId);

    /**
     * 
     * @param authToken
     * @param vmId
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "StopVm")
    @WebResult(partName = "return")
    public SystemStatus stopVm(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId);

    /**
     * 
     * @param authToken
     * @param vmId
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "SuspendVm")
    @WebResult(partName = "return")
    public SystemStatus suspendVm(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId);

    /**
     * 
     * @param authToken
     * @param vmId
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "ResumeVm")
    @WebResult(partName = "return")
    public SystemStatus resumeVm(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId);

    /**
     * 
     * @param ramSize
     * @param cpuCores
     * @param hdSize
     * @param authToken
     * @param vmId
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "ResizeComponents")
    @WebResult(partName = "return")
    public SystemStatus resizeComponents(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId,
        @WebParam(name = "ramSize", partName = "ramSize")
        int ramSize,
        @WebParam(name = "hdSize", partName = "hdSize")
        long hdSize,
        @WebParam(name = "cpuCores", partName = "cpuCores")
        int cpuCores);

    /**
     * 
     * @param authToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVmStatus")
    @WebResult(partName = "return")
    public String getVmStatus(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken);

    /**
     * 
     * @param authToken
     * @param vmId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVmIp")
    @WebResult(partName = "return")
    public String getVmIp(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "vmId", partName = "vmId")
        String vmId);

    /**
     * 
     * @param authToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBackendVersion")
    @WebResult(partName = "return")
    public String getBackendVersion(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken);

    /**
     * 
     * @param authToken
     * @param sourceUrl
     * @param version
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "UpgradeBackend")
    @WebResult(partName = "return")
    public SystemStatus upgradeBackend(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "version", partName = "version")
        String version,
        @WebParam(name = "sourceUrl", partName = "sourceUrl")
        String sourceUrl);

    /**
     * 
     * @param computerId
     * @param authToken
     * @return
     *     returns org.azuremd.backend.webservice.SystemStatus
     */
    @WebMethod(operationName = "SetInitialParams")
    @WebResult(partName = "return")
    public SystemStatus setInitialParams(
        @WebParam(name = "authToken", partName = "authToken")
        String authToken,
        @WebParam(name = "computerId", partName = "computerId")
        String computerId);

}
